server:
  port: 6969

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/"
  application:
    name: Account Management

azure:
  application-insights:
    instrumentation-key: ${rpe.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
  id:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    tenant-guid: ${TENANT_GUID}
    token-provider: ${TOKEN_PROVIDER}
  user:
    identity-issuer: ${IDENTITY_ISSUER}
    password-policy: ${PASSWORD_POLICY}
    signInType: emailAddress
  table:
    connectionString: ${CONNECTION_STRING}
    tableName: ${TABLE_NAME}

