server:
  port: 6969

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  cloud:
    azure:
      active-directory:
        enabled: true
        profile:
          tenant-id: ${TENANT_ID}
        credential:
          client-id: ${CLIENT_ID}
          client-secret: ${CLIENT_SECRET}
        app-id-uri: ${APP_URI}
        authorization-clients:
          publicationServicesApi:
            authorization-grant-type: client_credentials
            scopes:
              - ${PUBLICATION_SERVICES_AZ_API}/.default
          subscriptionManagementApi:
            authorization-grant-type: client_credentials
            scopes:
              - ${SUBSCRIPTION_MANAGEMENT_AZ_API}/.default
  config:
    import: "optional:configtree:/mnt/secrets/pip-ss-kv/"
  jackson:
    parser:
      STRICT_DUPLICATE_DETECTION: true
  application:
    name: PIP Account Management
  datasource:
    driver-class-name: org.postgresql.Driver

    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    properties:
      charSet: UTF-8
    hikari:
      minimumIdle: 2
      maximumPoolSize: 10
      idleTimeout: 10000
      poolName: ConnectionPool
      maxLifetime: 7200000
      connectionTimeout: 30000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL81Dialect
        jdbc:
          lob:
            non_contextual_creation: true
    database: POSTGRESQL
    generate-ddl: 'true'
    hibernate:
      # this ensures the db persists after spring boot connection drops.
      ddl-auto: update
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 2MB

service-to-service:
  publication-services: ${PUBLICATION_SERVICES_URL:https://pip-publication-services.staging.platform.hmcts.net}
  subscription-management: ${SUBSCRIPTION_MANAGEMENT_URL:https://pip-subscription-management.staging.platform.hmcts.net}

azure:
  application-insights:
    instrumentation-key: ${INSTRUMENTATION_KEY:00000000-0000-0000-0000-000000000000}
  id:
    client-id: ${CLIENT_ID_B2C:00000000-0000-0000-0000-000000000000}
    client-secret: ${CLIENT_SECRET_B2C}
    tenant-guid: ${TENANT_GUID_B2C:00000000-0000-0000-0000-000000000000}
    extension-id: ${EXTENSION_ID:00000000-0000-0000-0000-000000000000}
    token-provider: "https://graph.microsoft.com/.default"
    b2c-url: ${IDENTITY_ISSUER}
  user:
    identity-issuer: ${IDENTITY_ISSUER:hmctspipnonprod.onmicrosoft.com}
    signInType: emailAddress
  blob:
    connection-string: ${CONNECTION_STRING}
    container-name: files

cron:
  media-application-reporting: "0 0 0 * * MON"
  account-verification-check: "00 01 08 * * *"

dbMigration:
  runOnStartup: ${RUN_DB_MIGRATION_ON_STARTUP:true}

verification:
  media-account-verification-email-days: 350
  media-account-deletion-days: 365
  aad-admin-account-sign-in-notification-days: 76
  aad-admin-account-deletion-days: 90
  idam-account-sign-in-notification-days: 118
  idam-account-deletion-days: 132
