server:
  port: 6969

management:
  endpoint:
    health:
      show-details: "always"
  endpoints:
    web:
      base-path: /
      exposure:
        include: health, info, prometheus

#If you use a database then uncomment below lines and update db properties accordingly
spring:
  config:
    import: "optional:configtree:/mnt/secrets/pip-shared-kv"
  application:
    name: Account Management

azure:
  opt:
    client-id: ${CLIENT_ID:00000000-0000-0000-0000-000000000000}
    client-secret: ${CLIENT_SECRET}
    tenant-id: ${TENANT_GUID:00000000-0000-0000-0000-000000000000}
  storage:
    connection-string: ${CONNECTION_STRING}
  application-insights:
    instrumentation-key: ${rpe.AppInsightsInstrumentationKey:00000000-0000-0000-0000-000000000000}
  id:
    client-id: ${CLIENT_ID}
    client-secret: ${CLIENT_SECRET}
    tenant-guid: ${TENANT_GUID}
    token-provider: "https://graph.microsoft.com/.default"
  user:
    identity-issuer: "pib2csbox.onmicrosoft.com"
    password-policy: DisablePasswordExpiration
    signInType: emailAddress
  table:
    connectionString: ${CONNECTION_STRING}
    tableName: "Subscribers"

