spring:
  flyway:
    enabled: true
  jpa:
    hibernate:
      # Set to update for functional tests, so it creates the environment in H2
      ddl-auto: update

admin:
  max-system-admin: ${MAX_SYSTEM_ADMIN_ACCOUNTS:2}
