spring:
  datasource:
    driver-class-name: org.testcontainers.jdbc.ContainerDatabaseDriver
    url: jdbc:tc:postgresql://localhost/pip
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
