name: pip-account-management
apiVersion: v2
appVersion: "1.0"
home: https://github.com/hmcts/pip-account-management
version: 0.0.48
description: Publishing & Information Account Management
maintainers:
  - name: HMCTS PIP Team
dependencies:
  - name: java
    version: 5.3.0
    repository: oci://hmctspublic.azurecr.io/helm
  - name: blobstorage
    version: 2.0.2
    repository: https://hmctspublic.azurecr.io/helm/v1/repo/
    condition: blobstorage.enabled
