java:
  aadIdentityName: pip
  ingressHost: pip-account-management.{{ .Values.global.environment }}.platform.hmcts.net
  applicationPort: 6969
  image: 'sdshmctspublic.azurecr.io/pip/account-management:latest'
  keyVaults:
    pip-sharedservice-kv:
      resourceGroup: pip-sharedservice-{{ .Values.global.environment }}-rg
      usePodIdentity: true
      secrets:
        - name: otp-app-pip-account-management-id
          alias: CLIENT_ID
        - name: otp-app-pip-account-management-pwd
          alias: CLIENT_SECRET
        - name: otp-tenant-id
          alias: TENANT_GUID
        - name: pipsharedservicesa-storageaccount-connection-string
          alias: CONNECTION_STRING
  environment: