java:
  aadIdentityName: pip
  ingressHost: pip-account-management.{{ .Values.global.environment }}.platform.hmcts.net
  applicationPort: 6969
  image: 'sdshmctspublic.azurecr.io/pip/account-management:latest'
  keyVaults:
    pip-ss-kv:
      excludeEnvironmentSuffix: false
      resourceGroup: pip-ss-{{ .Values.global.environment }}-rg
      usePodIdentity: true
      secrets:
        - name: auto-pip-<ENV>-pip-account-management-<ENV>-id
          alias: CLIENT_ID_B2C
        - name: auto-pip-<ENV>-pip-account-management-<ENV>-pwd
          alias: CLIENT_SECRET_B2C
        - name: b2c-tenant-id
          alias: TENANT_GUID_B2C
        - name: b2c-extension-app-id
          alias: EXTENSION_ID
        - name: shared-storageaccount-connection-string
          alias: CONNECTION_STRING
        - name: account-management-POSTGRES-DATABASE
          alias: DB_NAME
        - name: account-management-POSTGRES-PASS
          alias: DB_PASS
        - name: account-management-POSTGRES-PORT
          alias: DB_PORT
        - name: account-management-POSTGRES-USER
          alias: DB_USER
        - name: account-management-POSTGRES-HOST
          alias: DB_HOST
        - name: app-pip-account-management-id
          alias: CLIENT_ID
        - name: app-tenant-id
          alias: TENANT_ID
        - name: app-pip-account-management-scope
          alias: APP_URI
