java:
  aadIdentityName: pip
  ingressHost: pip-account-management.{{ .Values.global.environment }}.platform.hmcts.net
  applicationPort: 6969
  image: 'sdshmctspublic.azurecr.io/pip/account-management:latest'
  keyVaults:
    pip-ss-kv:
      resourceGroup: pip-ss-{{ .Values.global.environment }}-rg
      secrets:
        - name: otp-app-pip-account-management-id
          alias: CLIENT_ID
        - name: otp-app-pip-account-management-pwd
          alias: CLIENT_SECRET
        - name: otp-tenant-id
          alias: TENANT_GUID
        - name: shared-storageaccount-connection-string
          alias: CONNECTION_STRING
        - name: pip-shared-POSTGRES-DATABASE
          alias: DB_NAME
        - name: pip-shared-POSTGRES-PASS
          alias: DB_PASS
        - name: pip-shared-POSTGRES-PORT
          alias: DB_PORT
        - name: pip-shared-POSTGRES-USER
          alias: DB_USER
  environment:
