-- Remove new BUSINESS PROPERTY LIST
--
UPDATE subscription_list_type
SET list_type = ARRAY_REMOVE(list_type, 'BUSINESS_AND_PROPERTY_DIVISION_ROLLS_BUILDING_DAILY_CAUSE_LIST')
WHERE ARRAY_TO_STRING(list_type, '||') LIKE '%BUSINESS_AND_PROPERTY_DIVISION_ROLLS_BUILDING_DAILY_CAUSE_LIST%';
