-- Add BUSINESS_AND_PROPERTY_DIVISION_ROLLS_BUILDING_DAILY_CAUSE_LIST to subscription_list_type for existing CHD and KB lists
UPDATE subscription_list_type
  SET list_type = list_type || '{BUSINESS_AND_PROPERTY_DIVISION_ROLLS_BUILDING_DAILY_CAUSE_LIST}'
  WHERE ARRAY_TO_STRING(list_type, '||') LIKE '%CHANCERY_APPEALS_CHD_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%BUSINESS_LIST_CHD_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%COMMERCIAL_COURT_KB_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%FINANCIAL_LIST_CHD_KB_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%INSOLVENCY_AND_COMPANIES_COURT_CHD_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%INTELLECTUAL_PROPERTY_AND_ENTERPRISE_COURT_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%INTELLECTUAL_PROPERTY_LIST_CHD_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%LONDON_CIRCUIT_COMMERCIAL_COURT_KB_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%PATENTS_COURT_CHD_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%PROPERTY_TRUSTS_PROBATE_LIST_CHD_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%TECHNOLOGY_AND_CONSTRUCTION_COURT_KB_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%ADMIRALTY_COURT_KB_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%COMPANIES_WINDING_UP_CHD_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%COMPETITION_LIST_CHD_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%PENSIONS_LIST_CHD_DAILY_CAUSE_LIST%'
     OR ARRAY_TO_STRING(list_type, '||') LIKE '%REVENUE_LIST_CHD_DAILY_CAUSE_LIST%';
